### ISSUE TITLE
Cannot use a custom template for a subset of fields easily

### ISSUE THREAD

**Issue by arturmatos** [maraujop/django-crispy-forms#138]
This probably makes more sense with an example. I have a fairly complex form (tabs, lots of fields, etc...) which has a radio group with a text box, like this:

![Screen Shot 2013-01-02 at 11 24 04](https://f.cloud.github.com/assets/2996736/38092/4f19ef04-54cf-11e2-98dd-6cd66ac11d17.png)

These are 2 fields in the form - one for the radio option, another for the  dropdown. I want to use a custom template for the 2 fields and use crispy forms defaults for everything else. 

The problem is that is not very easy to do this with crispy forms at the moment. I cannot use Div layouts with a custom template because Divs pre-render the fields and pass only the HTML to the template, so I cannot iterate over choices on the radio group, etc.. Field objects with a custom template don't work either because they only accept a single field while I need to access both at the same time inside the template, i.e. they are tightly integrated.

What I did in the end was to implement a custom layout object like this:

```python
class CustomTemplateLayout(Layout):

    def __init__(self, *fields, **kwargs):
        self.fields = list(fields)
        self.template = kwargs.get('template', None)

    def render(self, form, form_style, context, template_pack=TEMPLATE_PACK):
        bound_fields = []
        for field in self.fields:
            if isinstance(field, unicode):
                field = str(field)
                # If `field` is not unicode then we turn it into a unicode string, otherwise doing
                # str(field) would give no error and the field would not be resolved, causing confusion
            else:
                field = str(unicode(field))

            field_instance = form.fields[field]

            bound_field = BoundField(form, field_instance, field)
            bound_fields.append(bound_field)

            if not field in form.rendered_fields:
                form.rendered_fields.add(field)

        return render_to_string(self.template, Context({'fields' : bound_fields}))
```

You pass it a set of fields and a template and it converts the fields to BoundFields, mark them as rendered and pass them to the template.

Is there any easier way to do this? If not, I'm happy cleaning this up and submit it as a patch. I'm not sure if this is a common use case, though.

**Comment by carltongibson** [comment]
I'm going to close this as it's not something we can take on right now.
