### ISSUE TITLE
CRISPY_TEMPLATE_PACK required ?

### ISSUE THREAD

**Issue by jbub** [maraujop/django-crispy-forms#237]
hi, upgrading from 1.3.2 to 1.4.0, is CRISPY_TEMPLATE_PACK now a required setting ? 

in crispy_forms_tags.py:

on line 17:
TEMPLATE_PACK = getattr(settings, 'CRISPY_TEMPLATE_PACK', 'bootstrap')

but on line 160: (settings refers to django.conf.settings)
'template_pack': settings.CRISPY_TEMPLATE_PACK 

i think it should be just TEMPLATE_PACK if its not required setting

thanks

**Comment by carltongibson** [comment]
Closing this in favour of #452. Please follow along there.
