### ISSUE TITLE
Remove individual label from django crispy form layout

### ISSUE THREAD

**Issue by tusharpucsd** [maraujop/django-crispy-forms#248]
self.helper = FormHelper()
		self.helper.form_method = 'POST'
		self.helper.form_class = 'form-horizontal'
		#self.helper.form_show_labels = False
		self.helper.show_label_first_name = False
		self.helper.layout = Layout( 
	       	Div(
                     Div(HTML("""<label> Trust Admin Name</label>""")),
			    Div(Field('first_name',label="", placeholder="First Name"), css_class='span3'),
				Div(Field('middle_name', label="", placeholder="middle Name"), css_class='span3'),
				Div(Field('last_name', label="", placeholder="last Name"), css_class='span3'),
			    ),	       
			Div(
				Div(Field('mobile_number', placeholder= "Mobile Number"), css_class='span6'),
				Div(Field('landline_number',placeholder="Landline Number"), css_class='span6'),
				),
			Div(
				Div(Field('email', placeholder="Email Address"), css_class='span6'),
				Div('', css_class='span6'),
				),
			)
        super(TrustAdministrationForm, self).__init__(*args, **kwargs)

I want to remove the "first_name", "middle_name" and "last_name" from form layout,  How ca i do this.

**Comment by PabloVallejo** [comment]
@notanumber, thanks it's working for us. :+1: 

```python
for field_name in self.fields:
    field = self.fields.get(field_name)
    field.widget.attrs['placeholder'] = field.label
    field.label = ''
```

**Comment by tusharpucsd** [comment]
Thanks all..

**Comment by WayneLambert** [comment]
Just in case of anyone Googling this and landing here (like me), an approach that worked for me was:

```python
from crispy_forms.helper import FormHelper
from django import forms
...

class MyForm(forms.ModelForm):

    class Meta:
        model = MyModel
        fields = '__all__'
        unlabelled_fields = ('unlabelled_field_1', 'unlabelled_field_2')

    def __init__(self, *args, **kwargs):
        super(MyForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = True
        for field in MyForm.Meta.unlabelled_fields:
            self.fields[field].label = False
```

**Comment by mszahan** [comment]
thank youu
