### ISSUE TITLE
Problem including Media from custom widget

### ISSUE THREAD

**Issue by jmiller1** [maraujop/django-crispy-forms#263]
I've run into the same issue as this person on stackoverflow...

http://stackoverflow.com/questions/19543593/js-files-not-included-in-page-when-using-django-form-assets-media-class-with

The workaround of including {{ form.media }} in my template solved the issue, but I am curious if there is a way to support the default widget behavior of automatically including widget Media in the template page (without the tag). Thanks!

**Comment by carltongibson** [comment]
Closing this in favour of #452. Please follow along there.

(If you still have this problem after the new release, shout and we can reopen)

**Comment by frmdstryr** [comment]
Could this be made optional?  For multiple forms (formsets) this makes it include the css/js files every time.

**Comment by savingschampion** [comment]
+1
