### ISSUE TITLE
bootstrap3 form-horizontal: CheckboxInput not properly rendered

### ISSUE THREAD

**Issue by mrechte** [maraujop/django-crispy-forms#267]
Setting:
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3'
        self.helper.field_class = 'col-md-9'

Does not render check boxes in the expected column. This is the wrong rendered layout for a check box:

<div class="form-group">
    <div id="div_id_is_public" class="checkbox">
        <div class="controls col-lg-offset-0 col-md-9">
            <label for="id_is_public" class="">
                <input checked="checked" class="checkboxinput checkbox" id="id_is_public" name="is_public" type="checkbox" />Publique
            </label>
        </div>
    </div>
</div>

Not conform to http://getbootstrap.com/css/#forms

Thanks

**Comment by carltongibson** [comment]
Closing this in favour of #452. Please follow along there.

(If you still have this problem after the new release, shout and we can reopen)
