### ISSUE TITLE
bootstrap3 form-horizontal - StrictButton alignment

### ISSUE THREAD

**Issue by tittoto** [maraujop/django-crispy-forms#268]
Setting:
self.helper.form_class = 'form-horizontal'
self.helper.label_class = 'col-lg-2'
self.helper.field_class = 'col-lg-8'
helper.layout = Layout(
    'email',
    'password',
    'remember_me',
    StrictButton('Sign in', css_class='btn-default'),
)

Does not render the button like the documentation screenshot. It is aligned to the labels instead of the fields.

Not conform to https://django-crispy-forms.readthedocs.org/en/latest/crispy_tag_forms.html#bootstrap3-horizontal-forms

Thanks!

**Comment by carltongibson** [comment]
Closing this in favour of #452. Please follow along there.

(If you still have this problem after the new release, shout and we can reopen)

**Comment by ataylor32** [comment]
This is still an issue for me. I tried version 1.6.0 and also the dev branch.

**Comment by slavogiez** [comment]
I had the same problem. I just wrapped the StrictButton into a FormActions as mentionned [here](http://django-crispy-forms.readthedocs.io/en/latest/layouts.html#bootstrap-layout-obj) :

self.helper.layout = Layout(
   'email',
   'password',
   'remember_me',
   FormActions(
      StrictButton('Sign in', css_class='btn-default')
   ),
)
