### ISSUE TITLE
The attrs field cannot be defined in a FormHelper subclass.

### ISSUE THREAD

**Issue by alanwj** [maraujop/django-crispy-forms#308]
For most fields the following syntax works:
```
class MyFormHelper(FormHelper):
    form_class = 'form-horizontal'
```

But the following does not work:
```
class MyFormHelper(FormHelper):
    attrs = {'some-attribute': 'some-value'}
```

The only way accomplish this in a FormHelper subclass appears to be:
```
class MyFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(MyFormHelper, self).__init__(*args, **kwargs)
        self. attrs = {'some-attribute': 'some-value'}
```

This appears to be because FormHelper.__init__ overwrites attrs (rather than it being defined at the class level).  See:
https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/helper.py#L208

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
