### ISSUE TITLE
Setting "label_class" and "field_class" individually for each field

### ISSUE THREAD

**Issue by speendo** [maraujop/django-crispy-forms#348]
Referring to the documentation, it is easy to change the column widths of labels and fields of complete horizontal forms using bootstrap and crispy-forms (see here: http://django-crispy-forms.readthedocs.org/en/latest/crispy_tag_forms.html#bootstrap3-horizontal-forms)

However, I don't find a way to determine the width of just *one* input field. For example, in my form I have a color-input. As this input would never contain more than 6 characters, it's unnecessary that this field covers the whole page-width. I would rather add the classes "col-md-2 col-xs-3" to that input to make it smaller.

As far as I can see this is not easy to achieve at the moment.

Also see this question: http://stackoverflow.com/questions/24812267/crispy-forms-add-css-class-for-one-of-the-inputs/

**Comment by gtbae** [comment]
I have same problem. And I can't find a solution yet, too.

**Comment by dbrgn** [comment]
Same here. There's also someone on SO that would benefit from a solution:http://stackoverflow.com/questions/24812267/crispy-forms-add-css-class-for-one-of-the-inputs

My workaround is a custom field template, but that's way overkill.

**Comment by codister** [comment]
I can't seem to figure it out as well can some one propose a solution?

**Comment by neuroticnerd** [comment]
+1 I've just run into this as well; somewhat frustrating that something seemingly so simple takes such a disproportionate amount of time to work around :\

**Comment by carltongibson** [comment]
You should be creating project specific templates for cases like this. 

The bottom line is we can't include and maintain templates that cover every use-case. We cover the 80:20; the rest is up to individual users. 

If someone can come up with a simple, generic solution then a pull request will be favourably reviewed. Until then I'm going to close this as out of scope.

**Comment by baxeico** [comment]
For those looking for a solution for specific horizontal fields, I came up with this pure CSS solution using Boostrap5 classes:

```
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Layout

class HorizontalField(Field):

    def __init__(self, *fields, **kwargs):
        super().__init__(*fields, wrapper_class='d-flex justify-content-between align-items-center', css_class='w-75', **kwargs)

class MyForm(forms.Form):
    field1 = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HorizontalField('field1')
        )
