### ISSUE TITLE
Cannot override template on dev branch

### ISSUE THREAD

**Issue by johnraz** [maraujop/django-crispy-forms#361]
```
File "/home/vagrant/.virtualenvs/someproject/lib/python2.7/site-packages/crispy_forms/bootstrap.py" in render
  185.         template = self.template % template_pack

Exception Type: TypeError at /login/
Exception Value: not all arguments converted during string formatting
```

I get the above mentioned exception when overriding the template attribute on the helper.
It seems that the code always expect a template_pack placeholder to be present in the string which shouldn't always be the case, one should be able to completely override the template path.

Before submitting a PR I think its needed to have a design decision on what this should be doing, should we allow bare replacement of the template or should we document that the template_pack being used should be provided as a placeholder in the string...

anyone ?

**Comment by marshalc** [comment]
I can say I've hit this challenge just now myself. Am looking at the issue, though I am erroring out at `crispy_forms/layout.py in render, line 439` which is also `template = self.template % template_pack`

**Comment by marshalc** [comment]
As I see it, the basic problem is that the render line assumes that the template value will still be the pre-set string with expects a string value to be inserted (i.e. is `template = "%s/field.html"`). When you specify your own template override, this breaks the assumption. 

My current workaround is to wrap the render string with:
```
        if '%s' in self.template:
            template = self.template % template_pack
        else:
            template = self.template
```

**Comment by RafaelOrtiz** [comment]
Also hit this bug.

**Comment by damienjones** [comment]
Just updated to crispy 1.5 from 1.4 and got bitten with this. Now I get to decide whether to roll back to 1.4 or try to temporarily fork 1.5 to patch the bug (so I have a reproducible deployment process) using @marshalc fix.

**Comment by damienjones** [comment]
There are multiple instances of this problem in crispy_forms/layout.py.

**Comment by carltongibson** [comment]
@damienjones first off, if it works with 1.4 rollback to that — that one is easy.

> there are multiple instances...

That's not helpful. I need specifics. Preferably with test cases and maybe fixes in pull requests.

This has been in the Dev branch for 2 years. It's a shame no one ran it against their app to find the problem before now. However, let's get it fixed for a quick 1.5.1

**Comment by damienjones** [comment]
@carltongibson I was not intending to be unhelpful; I'm actually very appreciative of crispy-forms. I was going to submit a PR but I'm not set up to run the test suite and can't really stop what I'm doing at the moment to address that, and I wasn't comfortable submitting a PR that I hadn't personally tested. On top of that, it was @marshalc who suggested the fix that worked for me. I just applied it to my installed code so I can keep working on my main project today. If I get time tonight I'll see about replicating (and testing) the fix and submitting a PR.

**Comment by carltongibson** [comment]
Good man! 👍🏽

**Comment by carltongibson** [comment]
Have opened #493 to address. Please review.
