### ISSUE TITLE
Use with Django 1.7 throws RemovedInDjango18Warning

### ISSUE THREAD

**Issue by tayden** [maraujop/django-crispy-forms#370]
Running crispy forms under Django 1.7 produces the following warning:

    C:\(path to virtualenv)\lib\site-packages\crispy_forms_utils.py:92 RemovedInDjango18Warning: `is_hidden` property is now ready-only (and checks `input_type`). Please update your code.
        field_instance.widget.is_hidden = True

Everything runs ok, but I suspect utils.py will need to be updated soon to deal with this.

**Comment by jcomeauictx** [comment]
pull request 417 should fix this and other issues, hopefully without breaking anything new. it might be a little slower due to debug code though. I should be removing that soon.

**Comment by carltongibson** [comment]
Closing this in favour of #452. Please follow along there.
