### ISSUE TITLE
No module named 'crispy_forms'

### ISSUE THREAD

**Issue by jayadeepk** [maraujop/django-crispy-forms#377]
I have installed ```django-crispy-forms``` in python3 using virtualenv. Then added it to installed apps.
```
INSTALLED_APPS = (
    'crispy_forms',
```

In a template, I used it as follows
```
{% load crispy_forms_tags %}
   
<form action="/your-name/" method="post">
    {% csrf_token %}
    <table>
        {{ crispy form }}
    </table>
    <input type="submit" value="Submit" />
</form>
```

 But when I try to run the server from the terminal, it says "no module named 'crispy_forms'
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.8.dev20141008221050-py3.4.egg/django/core/management/__init__.py", line 336, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.8.dev20141008221050-py3.4.egg/django/core/management/__init__.py", line 310, in execute
    django.setup()
  File "/usr/local/lib/python3.4/dist-packages/Django-1.8.dev20141008221050-py3.4.egg/django/__init__.py", line 23, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.8.dev20141008221050-py3.4.egg/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.4/dist-packages/Django-1.8.dev20141008221050-py3.4.egg/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2201, in _find_and_load_unlocked
ImportError: No module named 'crispy_forms'
```

**Comment by catonalake** [comment]
Hi - was wondering if this issue was every resolved?  I'm running into a similar issue with a site i created on PythonAnywhere.  What is bizarre is that it DOES work on another site i have.. so i am guessing it is some kind of odd setting.. I've checked my virtual environments have all the items installed... 

thanks in advance for your insights here.

**Comment by carltongibson** [comment]
Open a shell and make sure you can import Crispy Forms without error. 

```
$ python -V
Python 3.5.0
$ ./manage.py shell
...
>>> import crispy_forms
>>> crispy_forms
<module 'crispy_forms' from '.../venv/lib/python3.5/site--packages/crispy_forms/__init__.py>
```

It's a project config error. Exactly what I'm afraid I can't say. :-(

I'm going to close this as it's not an issue with Crispy Forms _per se_. (I'm happy to accept PRs on the docs if you find what's wrong and it's a vagueness there. I'm happy to look at reproducible issues. etc)

**Comment by catonalake** [comment]
Hi Carlton,

thanks for the reply. :)

As you guessed, this import didn't work - my questions is more related to
the sys.path - and this:

Should the sys.path that i shared and highlighted in red be the issue?
 e.g. i  noticed that python3 dist-packages is listed but i am using
python3.4

>> print (sys.path)
['/var/lib/python3.4/site-packages', '/var/www', '/usr/lib/python3.4',
'/usr/lib/python3.4/plat-x86_64-linux-gnu', '/usr/lib/python3.4/lib
-dynload', '/usr/local/lib/python3.4/dist-packages',
'/usr/lib/python3/dist-packages',
'/home/cathleen/GitProjects/dav-test/votersite', '/
home/cathleen/GitProjects/dav-test', '/home/cathleen/GitProjects']
>>>

Thanks for your help!

**Comment by catonalake** [comment]
for more context:

here is my pip list:
(mydevvenv) 11:13 ~/GitProjects/dav-test (master)$ pip freeze
-f /usr/share/pip-wheels
click==6.6
decorator==4.0.9
Django==1.9.6
django-crispy-forms==1.6.0
django-filter==0.13.0
django-registration-redux==1.4
geocoder==1.15.0
mysqlclient==1.3.7
ratelim==0.1.6
requests==2.10.0
six==1.10.0

here is my installed apps and crispy settings in settings.py:
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'registration',
    'elections',
    'django.contrib.admin',
    )

#crispy form tag settings
CRISPY_TEMPLATE_PACK = 'bootstrap'

I actually have a paid account and was just setting this up temporarily to
test out some changes before i deployed to production.... which is why i am
baffled why it doesn't work in this environment - same settings, etc..

thank you!

**Comment by carltongibson** [comment]
Are you sure you activated you virtualenv? 

I'm expecting to see an entry like this in `sys.path`: 

      /path/to/mydevvenv/lib/python3.4/site-packages'

It doesn't seem to be there.

**Comment by hamzawan** [comment]
Thanks @carltongibson  thanks for the solution.

**Comment by Osemeke10** [comment]
currently facing this same challenge now, Can anyone help?

**Comment by smithdc1** [comment]
What happens when you try the suggestion above? 

https://github.com/django-crispy-forms/django-crispy-forms/issues/377#issuecomment-223882332

**Comment by Osemeke10** [comment]
I get  same error .


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by smithdc1** [comment]
Ok, and if you run `pip freeze` from your command prompt?

**Comment by Osemeke10** [comment]
altair==4.1.0
argon2-cffi==20.1.0
asgiref==3.4.1
astor==0.8.1
attrs==21.2.0
backcall==0.2.0
backports.entry-points-selectable==1.1.0
base58==2.1.0
bleach==4.0.0
blinker==1.4
cachetools==4.2.2
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.4
click==7.1.2
colorama==0.4.4
debugpy==1.4.1
decorator==5.0.9
defusedxml==0.7.1
distlib==0.3.2
dj-database-url==0.5.0
Django==3.2.6
django-crispy-forms==1.12.0
django-debug-toolbar==3.2.1
django-heroku==0.3.1
entrypoints==0.3
filelock==3.0.12
gitdb==4.0.7
GitPython==3.1.18
gunicorn==20.1.0
idna==3.2
ipykernel==6.2.0
ipython==7.26.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==3.0.1
jsonschema==3.2.0
jupyter-client==7.0.1
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
libretranslatepy==2.1.1
lxml==4.6.3
MarkupSafe==2.0.1
matplotlib-inline==0.1.2
mistune==0.8.4
nbclient==0.5.4
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.3
numpy==1.21.2
oauthlib==3.1.1
packaging==21.0
pandas==1.3.2
pandocfilters==1.4.3
parso==0.8.2
pathlib==1.0.1
pickleshare==0.7.5
Pillow==8.3.1
pipenv==2021.5.29
platformdirs==2.0.2
pluggy==0.13.1
prometheus-client==0.11.0
prompt-toolkit==3.0.20
protobuf==3.17.3
psycopg2==2.9.1
pyarrow==5.0.0
pycparser==2.20
pydeck==0.6.2
Pygments==2.10.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.1
pywin32==301
pywinpty==1.1.3
pyzmq==22.2.1
requests==2.26.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
Send2Trash==1.8.0
six==1.16.0
smmap==4.0.0
sqlparse==0.4.1
streamlit==0.87.0
terminado==0.11.1
testpath==0.5.0
toml==0.10.2
toolz==0.11.1
tornado==6.1
traitlets==5.0.5
translate==3.6.1
tzdata==2021.1
tzlocal==3.0
urllib3==1.26.6
validators==0.18.2
virtualenv==20.6.0
virtualenv-clone==0.5.6
virtualenvwrapper-win==1.2.6
watchdog==2.1.4
wcwidth==0.2.5
webencodings==0.5.1
whitenoise==5.3.0
widgetsnbextension==3.5.1
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by carltongibson** [comment]
@Osemeke10 — **Somehow** you haven't activated your `venv` — if crispy forms is installed then it will be importable. 

Try creating a fresh environment. Check `sys.path` and `sys.executable`. 

Sorry, this isn't something we can help you with here. Your environment isn't right, but saying exactly why not is impossible over an issue tracker.

**Comment by Osemeke10** [comment]
I have resolved the error.
Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
