### ISSUE TITLE
Bootstrap3 inline form not showing form errors

### ISSUE THREAD

**Issue by aps-sids** [maraujop/django-crispy-forms#382]
The errors upon form submission (like skipping required fields) are not being shown. They do in normal and horizontal form layouts.

This is how my code looks:

```python
# Models.py

class Person(models.Model):
    name = models.CharField(max_length=500)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    email = models.EmailField(blank=True)

# Forms.py

class EntryForm(forms.ModelForm):
    class Meta:
        model = Person

    def __init__(self, *args, **kwargs):
        super(EntryForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-inline'
        self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.layout.append(ButtonHolder(
            Submit('save', 'Save', css_class='btn-primary btn-hg')
            )
        )
```

I am using `{% load crispy_forms_tags %}` and `{% crispy form %}` in my template.

**Comment by dbrgn** [comment]
Same here.

There are also some people on SO having this problem:

- http://stackoverflow.com/questions/26863624/bootstrap3-inline-forms-in-django-crispy-forms-not-showing-form-errors
- http://stackoverflow.com/questions/19094974/rendering-field-errors-in-django-crispy-forms-with-inline-forms

Custom templates are definitely not a viable solution. This is a bug in django-crispy-forms.

**Comment by aps-sids** [comment]
@dbrgn Actually, I had posted the first SO question. Never found out a good solution. No one replied on this thread either.

**Comment by carltongibson** [comment]
> Custom templates are definitely not a viable solution.

Why not? 

In general I would expect users to be creating per-project templates for their specific needs. The core template packs need to aim for the 80:20, balancing use-case coverage against simplicity and ease of maintenance. 

I'd consider a pull request showing how this use-case can be addressed simply in the core template pack but given the current resources I'm going to close it as out of scope pending that.

**Comment by dbrgn** [comment]
> Why not?

Not because of technical reasons, but because the current solution is inconsistent: Almost all form fields show errors by default, but the InlineFormFIeld does not.

I think custom templates should only be used to add functionality that deviates from the "standard use case", which is showing form fields, validating them and showing errors.

I understand that your time is limited, but maybe we can keep this issue open until someone proposes a PR? I might find the time to do so in the next few days, can't guarantee it though.

**Comment by carltongibson** [comment]
> maybe we can keep this issue open until someone proposes a PR?

No. Sorry. That's not how we need to run the issue tracker. [See here for more details](http://www.dabapps.com/blog/sustainable-open-source-management/)

I'm happy for people to comment on closed issues, and to review PRs if and when they appear, but I need to close issues that we don't have time to address.

**Comment by dbrgn** [comment]
@carltongibson that's a great article, thanks. I'll keep it in mind, and maybe I can provide a PR :)

**Comment by Eraldo** [comment]
I am subject to the same issue. :|

Would be glad if this ticket could be reconsidered.

**Comment by carltongibson** [comment]
Again, happy to review a documented, tested, PR but other than that have to recommend the custom template.

**Comment by Eraldo** [comment]
Understandable.. and good to know that PRs are welcome. :D
