### ISSUE TITLE
Tests Fail with Django v1.4.16

### ISSUE THREAD

**Issue by dashdrum** [maraujop/django-crispy-forms#383]
Two tests in test_layout.py fail with Django version 1.4.16 - test_formset_layout() and test_modelformset_layout().

Seems to be a problem with version comparison.  I have submitted a pull request.

**Comment by jcomeauictx** [comment]
using Django==1.7.3 and django-crispy-forms==1.4.0:

======================================================================
FAIL: test_formset_layout (crispy_forms.tests.test_layout.TestFormLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jcomeau/rentacoder/jhorton/obot/obot/venv/local/lib/python2.7/site-packages/crispy_forms/tests/test_layout.py", line 393, in test_formset_layout
    self.assertEqual(html.count("hidden"), 4)
AssertionError: 5 != 4

dashdrum's observation may be correct, inasmuch as string comparisons are being used on what should be a special comparator for version numbers. however, I suspect there are other issues. I just don't want to take time at the moment to track down where it's getting the form with these "hidden" fields.

**Comment by dashdrum** [comment]
Pull request #369 solves the 'basestring' error that I'm seeing with Python 3.3. and Django 1.5.1.

**Comment by jcomeauictx** [comment]
pull request #417 fixes the assertion error. it was due to the addition of MIN_NUM_FORM_COUNT in Django 1.7.

**Comment by maraujop** [comment]
Fix in dev branch now, see #417 thanks

Please read my changelog:
2b808e9#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR9

Cheers,
Miguel
