### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joshk0** [maraujop/django-crispy-forms#393]
Is there a new release planned for pypi soon?

There have been many fixes and commits but I am hesitant to put a dev release in my requirements.txt.

Thanks!

**Comment by shulcsm** [comment]
Yep, i'm having same issue. Multiple issues that have been fixed but last release on 2013-09-01.

**Comment by marc-gist** [comment]
also, any new development planned? or is this it for features/etc?

**Comment by aklaver** [comment]
Yes, it would be nice to see some sort of development timetable or a state of the project statement.

**Comment by joshk0** [comment]
Maybe it's time to fork this baby and continue on if anyone is interested.

**Comment by Zopieux** [comment]
It would be much more convenient if @maraujop could give write or admin access to someone ready to adopt the project, so Pypi stays up-to-date. Forking is easy but not convenient at all for end users.

**Comment by baxeico** [comment]
Seems that there are some hope to see @maraujop back to work on the project. See https://twitter.com/maraujop/status/575303590698483712

**Comment by bogdal** [comment]
:+1: It would be great to see a new release.

**Comment by adrienbrunet** [comment]
:+1: Still waiting :pensive:

**Comment by michaeljones** [comment]
+1

If it can't be done easily, is there someone who has followed the development who can recommend a good SHA1 to work with? I'm getting warnings from Django 1.7 and would like to update.

**Comment by freakypie** [comment]
+1

**Comment by kuanyui** [comment]
+1

The warning `venv/lib/python3.3/site-packages/crispy_forms/utils.py:25: RemovedInDjango19Warning: memoize wrapper is deprecated and will be removed in Django 1.9. Use django.utils.lru_cache instead.` keeps showing in the latest release...

**Comment by acidjunk** [comment]
+1

**Comment by luk156** [comment]
+1

**Comment by carltongibson** [comment]
Closing this in favour of #452. Please follow along there.
