### ISSUE TITLE
Slow rendering on Django 1.7 if Layout objects

### ISSUE THREAD

**Issue by aRkadeFR** [maraujop/django-crispy-forms#398]
Hello,

I've been using django crispy forms for quite a while now, and never noticed this issue until now. Maybe it comes from my syntax uising the Layout and Div object. I have DCF 1.4.0.

As soon as I'm using the layout.Layout object with some div inside, the time for rendering the form is extremely slow (1.5 second instead of 100ms).

I have a very simple form: 
```
class TAFilterForm(forms.Form):
    subject = forms.CharField(required=False)
    ss = forms.ChoiceField(choices=models.SS_CHOICES, required=False)
    min_created_at = forms.DateField(required=False)
    max_created_at = forms.DateField(required=False)
    aa = forms.ChoiceField(choices=models.AA_CHOICES, required=False)
    cc = forms.ChoiceField(required=False)
    id = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super(TAFilterForm, self).__init__(*args, **kwargs)
        self.fields['cc'].choices = (('all', _('All')), )
        self.helper = helper.FormHelper()
        self.helper.form_method = 'GET'
        self.helper.add_input(
            layout.Submit('submit', _('Filter')),
        )
        self.helper.add_input(
            layout.Submit('csv', _('Get CSV')),
        )
        self.helper.layout = layout.Layout(
            layout.Div(
                layout.Div('id', css_class='span3'),
                layout.Div('ss', css_class='span3'),
                layout.Div('aa', css_class='span3'),
                layout.Div('cc', css_class='span3'),
                css_class='row-fluid filter-form-div',
            ),
            layout.Div(
                layout.Div('subject', css_class='span4'),
                layout.Div('min_created_at', css_class='span4'),
                layout.Div('max_created_at', css_class='span4'),
                css_class='row-fluid filter-form-div',
            ),
        )
```

thanks

**Comment by robbyt** [comment]
This project has been super quiet for the past year. I suggest profiling
your python code to find the source of the slowness.

**Comment by rafelbennasar** [comment]
I have exactly the same problem with django 1.7.4 and I never had noticed this before.

With the self.helper.layout: 3.2 s.
without: 400ms.

**Comment by WST** [comment]
Same problem here. Makes my app running slow on Raspberry Pi (pages without forms are rendered a lot faster).

**Comment by krtek4** [comment]
I can confirm using the Layout object still leads to huge slowdown on Django 1.9 with Cryspi forms 1.6

**Comment by rfj001** [comment]
Using django's cached template loader helps speed things up immensely. 

Use this code use the cached template loader.
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
            ],
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]
```

Without caching even without a Layout object crispy forms seems to take forever to render forms with many fields or formsets with many forms. By using the loader I brought a formset with 8 forms of 3 fields each from 10s rendering time down to 500ms on subsequent loads.

**Comment by carltongibson** [comment]
It's worthing looking at the FAQ, which discusses this too. http://django-crispy-forms.readthedocs.io/en/latest/faq.html?highlight=cache#how-fast-is-django-crispy-forms

I'm going to close this as I don't think it's an issue per se. (Happy to reconsider if enlightened suggestions arise.)
