### ISSUE TITLE
why the last version is not available in PyPI?

### ISSUE THREAD

**Issue by pajooh** [maraujop/django-crispy-forms#403]

**Comment by baxeico** [comment]
Last release on github is 1.4.0, you can get it from PyPI here:

https://pypi.python.org/pypi/django-crispy-forms/1.4.0

**Comment by pajooh** [comment]
I see in the CHANGELOG that there is a 1.5.0 release

**Comment by baxeico** [comment]
I see. I don't know the answer to your question, I think @maraujop should answer, but I see very small activity from him in the repository in the last months.

**Comment by gtrman** [comment]
Yes, very little activity. 1.5.0 fixes a bug with bootstrap templates though. Next to that, I used it for some time already without an problems. Would be nice if it could be available thru PyPi anway ...

**Comment by baxeico** [comment]
@gtrman how do you installed the 1.5.0 version? I cannot see even a tag in the github repository. Thank you!

**Comment by hwkns** [comment]
There is no tag because 1.5.0 is still in development; you can see https://github.com/maraujop/django-crispy-forms/commit/3a973063cd0e845bab5168cf10d94a4ba10b4528 which makes way for the "future" release, and several commits after that updating `CHANGELOG`, but the maintainer doesn't consider it to be a full release yet.

**Comment by esitarski** [comment]
The 1.7.7 and 1.8 release of django cause warnings:

- memoize is deprecated - replaced by lru_cache
- is_hidden is no longer a writeable attribute

These look like simple fixes that have already been addressed.
Any timeline when there might be a pypi release to address these minor issues?

**Comment by Kobold** [comment]
+1 Seeing these issues. Would love to have a quick release cut.

**Comment by carltongibson** [comment]
Closing this in favour of #452. Please follow along there.
