### ISSUE TITLE
'form_class' not in context

### ISSUE THREAD

**Issue by codingjoe** [maraujop/django-crispy-forms#418]
The variable `form_class` is not in the context if you use the template filter `as_crispy_field`.

https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templates/bootstrap3/field.html#L14

https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templatetags/crispy_forms_filters.py#L107-L108

**Comment by carltongibson** [comment]
Can't find a reference to `form_class` in https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templates/bootstrap3/field.html — so I can't see the issue.

**Comment by codingjoe** [comment]
Seems to be fixed in the past. Thanks for checking up on this.
