### ISSUE TITLE
Semantic-UI support

### ISSUE THREAD

**Issue by acidjunk** [maraujop/django-crispy-forms#425]
I'm working on a semantic-ui based project. What would be the best way to start working on a new CRISPY_TEMPLATE_PACK? Just Fork the project and then copy one of the already existing template folders?

**Comment by acidjunk** [comment]
I started working on semantic-ui support; will send you a pull request when ready.

**Comment by michaelfillier** [comment]
@acidjunk Did you get anywhere with Semantic-UI integration? Working on a project right now that needs it, wondering if I need to start from scratch.

**Comment by acidjunk** [comment]
Yo michiel: I started working on it: what I have so far (only form input types that I needed so far)
->
https://github.com/acidjunk/crispy-forms-semanticUI-templates

You can overrule templates only but it would be nice to have it included in Django-Cripsy-Forms itself.
(seems that pull request aren't done ATM)

any help to a complete a testable semantic-UI theme for Django Crispy Forms is appreciated. I basically started hacking now in one of the other themes until it worked enough ;)

**Comment by carltongibson** [comment]
Happy to review a PR on the Docs adding a "Third-Party Template Packs" section for completed template packs.

**Comment by acidjunk** [comment]
+1 for Third Part Template pack docs

I can send a PR for the template pack itself: but I would like to run tests firsts. It working quite nice for our own project but we didn't use all possible form combo's yet.
