### ISSUE TITLE
Deprecation in Django 2.0: "render() must be called with a dict, not a Context."

### ISSUE THREAD

**Issue by Ernir** [maraujop/django-crispy-forms#429]
The warning message:

    [mypath]/venv/lib/python3.4/site-packages/crispy_forms/templatetags/crispy_forms_tags.py:217: RemovedInDjango20Warning: render() must be called with a dict, not a Context.
    return template.render(c)

I am running django 1.8 and django-crispy-forms 1.4.0 on Python 3.

As far as I can tell, the warning originates from https://docs.djangoproject.com/en/1.8/_modules/django/template/backends/django/

**Comment by kavdev** [comment]
Just a note: this is duplicated by #553

**Comment by carltongibson** [comment]
Closed by #555 — Any more pop up, open a new ticket.
