### ISSUE TITLE
Add `Layout.__repr__` and `FormHelper.__repr__` for easier debugging 

### ISSUE THREAD

**Issue by cool-RR** [maraujop/django-crispy-forms#434]

**Comment by michaeljones** [comment]
Hey,

That is a pretty minimalist issue report :) Considering the maintainer of this project seems to be having trouble with finding the time to work on it, it might be worth trying to include as much detail as possible.

What sort of things would you like to see in the `repr` output? What are you hoping to understanding from being able to print that out?

Cheers,
Michael

**Comment by cool-RR** [comment]
Hello Michael,

I've only started working with Crispy so I'm not sure which details are the
most important to show. I hope I don't have to explain how helpful it is,
during debugging, to be able to see details about object and inspect them
without having to access attributes manually.

Given that the above fact is understood by everyone, I think it's quite
easy to come up with a nice `__repr__`. Just as an example: If you have a
`Layout` object, then maybe a truncated list of items in it? So if it's
just three or four items, show all of them, but if it's more, show the
first 2-3 items, then [...], and the last item, and then at the end show
the count: `(7 items)`.

This is just a suggestion off the top of my head that would improve the
debugging situation. I'm sure that people who've been using Crispy more
than me will be able to come up with better ways. Of course, assuming
people have the time to work on this.


Thanks,
Ram.

**Comment by carltongibson** [comment]
> I think it's quite easy to come up with a nice `__repr__`

Dead right. But I'm going to close this as an active issue. If a PR turns up it'll be favourably reviewed.
