### ISSUE TITLE
Unicode error when unicode characters are included in the HTML object

### ISSUE THREAD

**Issue by guocheng** [maraujop/django-crispy-forms#435]
Hello,

I have encountered an unicode error when I try to insert a HTML object into a form layout. My code is like this:

```python
class AForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        ...
        self.helper[12] = HTML("""
        <p>some unicode characters in here</p>
        """)
```

I used the **p** tag as an example but you get the idea. If I remove the unicode characters, the error goes away and everything would render properly. I had to pass the unicode characters as part of the context to the form and do this to get around:

```python
        self.helper[12] = HTML("""
        <p>{{ unicode_message }}</p>
        """)
```

I would like to know if this is a bug or if it is just me being silly without aware of a better way to deal with this.

Thanks!

**Comment by michaeljones** [comment]
What version of Python are you using out of interest? And are you using unicode literals?

Cheers,
Michael

**Comment by guocheng** [comment]
Ah, unicode literals, I forgot about it... for some reason I thought the HTML(""" """) will just paste whatever inside into the final html page.

Thanks Michael, a stupid mistake on my part.
