### ISSUE TITLE
Cannot set Field to type='hidden' in FormHelper

### ISSUE THREAD

**Issue by guocheng** [maraujop/django-crispy-forms#437]
I have a formset and a formhelp object.

```python
class MyHelper(FormHelper):
         def __init__(self, *args, **kwargs):
             super(MyHelper, self).__init__(*args, **kwargs)
             self.helper = FormHelper()
             self.layout = Layout(
                 Field('set_id', type='hidden', value='0')
             )
```

When I render this formset, I get this error:

```
can't set attribute
```

The line that causes this error is:

```
/Users/cheng/.virtualenvs/waimai/lib/python2.7/site-packages/crispy_forms/utils.py in render_field
92.                                        field_instance.widget.is_hidden = True 
```

When I remove the type='hidden' part from the Field definition, everything works. I don't know why I cannot set this field to hidden. Here is the model definition of this field:

```python
class Answer(models.Model):
    set_id = models.IntegerField()
```

Thanks for your help!

**Comment by michaeljones** [comment]
What version of Django are you using out of interest? I think things have changed with the handling of `hidden` in Django 1.8. I'm getting warnings about it in 1.7.

**Comment by guocheng** [comment]
I am using Django 1.8.2

**Comment by guocheng** [comment]
A work around I found, instead of setting the field to hidden in the FormHelper, I can set it when I create the modelformset:

```python
NoteFormSet = modelformset_factory(Answer, widgets={'set_id': forms.HiddenInput()}, extra=0)
```

**Comment by camillobruni** [comment]
Setting `field_instance.widget.input_type = 'hidden'` in utils.py:92 seems to work for me.
django.forms.widgets.Widget defines `is_hidden` only as a property.

**Comment by guocheng** [comment]
That's great to know, thank you @camillobruni  !

**Comment by kviktor** [comment]
Any ETA for PyPI release?

**Comment by AlejandroFrias** [comment]
+1 on ETA for PyPi release

**Comment by squ1b3r** [comment]
Is this ever going to be released? It's sitting in the dev branch for two years now.
