### ISSUE TITLE
Makefile: --use-mirrors has been deprecated

### ISSUE THREAD

**Issue by rm--** [maraujop/django-crispy-forms#438]
The `--use-mirrors` option should be replace by something other, because with `pip 6.0.8` there is the following deprecation warning: 
`DEPRECATION: --use-mirrors has been deprecated and will be removed in the future. Explicit uses of --index-url and/or --extra-index-url is suggested.`.

And with new version of `pip` like `7.0.3` it ends with an error: `no such option: --use-mirrors`.

**Comment by carltongibson** [comment]
Now fixed in `dev`. Ta.
