### ISSUE TITLE
Semantic UI template pack

### ISSUE THREAD

**Issue by alexey-grom** [maraujop/django-crispy-forms#439]
Hi!
Is it possible to put a link to [semantic ui template pack](https://github.com/alexey-grom/crispy-semantic-ui) somewhere?

**Comment by acidjunk** [comment]
WIP:
https://github.com/acidjunk/crispy-forms-semanticUI-templates

**Comment by acidjunk** [comment]
https://github.com/maraujop/django-crispy-forms/issues/425
(this one could be clode I think)

**Comment by carltongibson** [comment]
Happy to review a PR on the Docs adding a "Third-Party Template Packs" section for completed template packs.
