### ISSUE TITLE
form.media should be configurable in some manner

### ISSUE THREAD

**Issue by dwatkinsweb** [maraujop/django-crispy-forms#440]
Currently, most of the form templates are automatically including `{{form.media}}` automatically. I'm currently using requirejs to load my javascript and using form.media breaks the concept. For the moment, I copied your display_form.html into my root template directory and removed the `{{form.media}}` as a fix for now, but I think that the use of `form.media` should be configurable for those of us using requirejs or some other AMD javascript loading system. It might be nice to have it configurable at the root level (settings.py), form level, or possibly even as a parameter in the template tag. 

If I have time, I can look into it myself, but at the moment I cannot and I have a fix as well so unless anybody else has the same concern, it's probably not a huge priority.

**Comment by abbottc** [comment]
I would also like to see this feature, especially so that this project works nicely with utilities like django-compressor without needing to override crispy templates.  Perhaps one simple-to-implement option would be an `include_media` boolean that could be set on the FormHelper and a `CRISPY_INCLUDE_MEDIA` that could be in settings.py to have the same effect globally.  I could submit a pull request implementing this if the project maintainer is on board with the idea.

**Comment by hiltonc** [comment]
I would appreciate this as well. https://github.com/aljosa/django-tinymce is currently broken as-is when more than one TinyMCE field appears in a form because the JavaScript gets loaded multiple times.

**Comment by palm86** [comment]
Would be much appreciated. Autormatically including {{form.media}} breaks forms loaded by AJAX with custom widgets.

**Comment by carltongibson** [comment]
I'd consider a (documented, tested) pull request here

Would **much** rather an attribute on `FormHelper` than a setting. (Anyone wanting it globally is welcome to subclass `FormHelper`.)

**Comment by abbottc** [comment]
I've submitted a (documented, tested) pull request #525.  As per the conversation, it's implemented as an attribute on FormHelper and not a setting, with a note in the documentation about overriding FormHelper if a global change is desired.

**Comment by carltongibson** [comment]
Fixed by #525
