### ISSUE TITLE
Update Travis config

### ISSUE THREAD

**Issue by carltongibson** [maraujop/django-crispy-forms#450]
Step 1 is to get the test suite running against all current (and upcoming) versions of Django. 

Whilst we're there, clean up the version number for #443 "PEP 440 warning during installation".

Pinging #444 

* Drop support for Django 1.3. See f06ce0460b52605ee5916

**Comment by kevin-brown** [comment]
It looks like you don't need `sudo` for anything, so you might want to add

```yaml
sudo: false
```

To the tests to have them use the container based infrastructure.

**Comment by carltongibson** [comment]
Hey @kevin-brown, thanks for the pointer. We'll give that a go #454 :+1:
