### ISSUE TITLE
"Not a registered tag library" against Django Pre-1.9 master

### ISSUE THREAD

**Issue by carltongibson** [maraujop/django-crispy-forms#457]
Getting an error running against latest Django master: 

      TemplateSyntaxError: 'crispy_forms_tags' is not a registered tag library. Must be one of:

(Note there's literally nothing in the output after the `:` there — i.e. it looks like a list is expected but missing.)

[See here for an example build](https://travis-ci.org/maraujop/django-crispy-forms/builds/75753379)

**Comment by Stranger6667** [comment]
Probably caused by this [change](https://docs.djangoproject.com/en/dev/releases/1.9/#template-tag-modules-are-imported-when-templates-are-configured). I'll investigate about ways to fix it
