### ISSUE TITLE
Update PyPI uploads

### ISSUE THREAD

**Issue by carltongibson** [maraujop/django-crispy-forms#459]
Releasing v.1.5.0 I ran the customary `python setup.py sdist upload` — no problem. 

I then went for `python setup.py bdist_wheel upload` and got errors: 

```
Submitting dist/django-crispy-forms-1.5.0.tar.gz to http://pypi.python.org/pypi
Server response (200): OK
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```

1. This normally works. Why not here? 
2. OK... but we may as well review the best practices here whilst we've got the lid off. 

Following input from @kevin-brown:

* [ ] Add development requirements.

**Comment by kevin-brown** [comment]
> error: invalid command 'bdist_wheel'

Do you have the `wheel` package installed locally?

It might be useful to have a requirements file that includes it (along with any other development requirements).

**Comment by carltongibson** [comment]
@kevin-brown — Thanks for the input here! (I've had this going fine for Django Filter and was a little bemused by the error)

> Do you have the wheel package installed locally?

Not in the virtualenv. And looking at my DF setup, of course, there it is: 

```
~ $ workon django-filter
(django-filter)~/Documents/Django-Stack/django-filter (master)$ pip freeze | grep wheel
wheel==0.24.0
```

> It might be useful to have a requirements file that includes it (along with any other development packages).

Absolutely. :-)

**Comment by carltongibson** [comment]
I guess I just install and retry that now.

**Comment by carltongibson** [comment]
Right. And that worked. Thanks @kevin-brown! 

* [ ] Add development requirements. 

Looking at [DRF's setup.py](https://github.com/tomchristie/django-rest-framework/blob/master/setup.py#L54), do you happened to know what the `twine` bit is all about? (Ta!)

**Comment by kevin-brown** [comment]
> do you happened to know what the twine bit is all about?

[Twine](https://github.com/pypa/twine) appears to be a secure way to upload distributions to PyPI.

**Comment by carltongibson** [comment]
Good. The first paragraph of the README is about enough there. I'll add that tomorrow. 👍
