### ISSUE TITLE
Repeated tests execution

### ISSUE THREAD

**Issue by Stranger6667** [maraujop/django-crispy-forms#465]
Each test call for different template pack runs more tests, that it is required. Because of class inheritance.
E.g. bootstrap runs 134 tests now and before. But:
```TestFormHelper``` - has 22 tests
```TestBootstrapFormHelper``` - has 4 own tests and 22 from ```TestFormHelper```
So, these 22 tests runs twice. Same with all inherited test classes and other template packs. 
Real tests count:
* uni_form - 78 (139 before)
* bootstrap - 91 (134 before)
* bootstrap3 - 94 (175 before)

**Comment by Stranger6667** [comment]
Done in [77f9408d](https://github.com/Stranger6667/django-crispy-forms/commit/77f9408d081a57303703d9d02dd7dad43cc7a173). It is based on py.test branch (#464) and I'll create PR when py.test branch will be accepted.

**Comment by carltongibson** [comment]
OK. Good for a PR here. 

I looked at the commit. Can you take a moment to explain the skip logic in the description for me? A single example will do. It'll save me needing to think too hard. 😀 

Thanks!

**Comment by Stranger6667** [comment]
Sure, I'll add it in PR :)
