### ISSUE TITLE
Propose to remove global variables from module level

### ISSUE THREAD

**Issue by Stranger6667** [maraujop/django-crispy-forms#472]
I've faced with some problem when I was working on parametrization. The problem is [global variables](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/layout.py#L11) at module level, which came from ```django.conf.settings```.

It makes test parametrization very hard, because this variables uses as default values in methods signatures. Also it may leads to some potential problems with override_settings and so on.

My proposal is to remove ```TEMPLATE_PACK```, ```CRISPY_ALLOWED_TEMPLATE_PACKS``` and ```CRISPY_CLASS_CONVERTERS```, ```CRISPY_FAIL_SILENTLY``` evaluation from module level and make able to configure django-crispy-forms in runtime without reloading.

**Comment by carltongibson** [comment]
The goal here is to be able to run the whole test suite in one go, rather than three, right? — Happy to see a PR for that. If you're not sure how it will go, open a PR with your thoughts so far and we can discuss.

**Comment by carltongibson** [comment]
Fixed in #477
