### ISSUE TITLE
Consider testing against Django versions 1.4, 1.4.1, 1.4.2, 1.4.3

### ISSUE THREAD

**Issue by Stranger6667** [maraujop/django-crispy-forms#491]
In current test suite there are 2 places with conditions related to these versions.
[Here](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/tests/test_layout.py#L283) and [here](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/tests/test_layout.py#L348)
Also in travis config there are only latest versions of 1.4, 1.7, 1.8 and master branches.
My question is - Should we drop these conditions or add old Django version to config?
Personally, I prefer to drop.

**Comment by carltongibson** [comment]
I agree. Drop. We'll support the latest version of Django 1.4 until it's end of life. But we're not doing more than that.
