### ISSUE TITLE
self.helper.form_show_labels = False has no effect

### ISSUE THREAD

**Issue by smirolo** [maraujop/django-crispy-forms#504]
Hi,

I couldn't find any issue where this comment seemed to fit so I am opening a new one.

I use Python 2.7.10, Django 1.7.9, and django-crispy-forms 1.5.1 (though the problem seem to be present in the current dev branch as well).

What happens is that [crispy_forms_tags.py](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templatetags/crispy_forms_tags.py) contains the following statement:

    from crispy_forms.templatetags.crispy_forms_filters import *

Both crispy_forms_tags.py and [crispy_forms_filters.py](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templatetags/crispy_forms_filters.py) have the following statement:

    @register.filter(name='crispy')

As it turns out if the template contains the following code:

    {% load crispy_forms_tags %}
    {% crispy form %}

Then ``do_uni_form`` (crispy_forms_tags.py) is not called but ``as_crispy_form`` (crispy_forms_filters.py) is called instead. Since ``as_crispy_form`` contains an hard coded statement:

    ...
            'form_show_labels': True,
    ...

It turns out that whatever helper.form_show_labels is set to has no effect.

My guess is that Python loads crispy_forms_filters.py first, executes the Django code for ``register.filter``, then loads crispy_forms_tags.py and executes the Django code for ``register.filter``. This code silently skips over the second definition of "crispy" and thus execute a different code than the one intended when a ``{% crispy form %}`` statement is present in a template.

**Comment by Stranger6667** [comment]
Hello, 

> Both crispy_forms_tags.py and crispy_forms_filters.py have the following statement:
> `@register.filter(name='crispy')`

But in crispy_forms_tags.py there is `@register.tag(name="crispy")`. As follows, ```as_crispy_form``` is called in ```{{ form|crispy }}``` and ```do_uni_form``` is called in ```{% crispy form %}```. Can you provide some test case, when ```helper.form_show_labels``` has no effect?

Regards,

**Comment by smirolo** [comment]
Sorry for the delay.

1. Half of the analysis on my bug chase is incorrect. I was editing one template with {% crispy form %} and loading another almost similar template with {{form|crispy}}. The functions ``as_crispy_form`` and ``do_uni_form`` are called as expected.

2. ``'form_show_labels': True,`` is still the statement producing unexpected output. I have cloned the upstream repository at commit c8154d16 and created a testsite/ Django project at the top level (See: [commit c1a52748b](https://github.com/smirolo/django-crispy-forms/commit/c1a52748b7312dd360ce4cd5b820ee1aa1455224)). To try out:

        $ virtualenv tmp
        $ cd tmp
        $ source bin/activate
        $ git clone git@github.com:smirolo/django-crispy-forms.git
        $ cd django-crispy-forms
        $ python manage.py runserver

Now that I look at it, it seems like the ``form.helper`` in never used in the ``{{ form|crispy }}`` context. I don't know if it is intended by design. It is really odd.

How do I prevent showing the labels and use the ``{{ form|crispy }}`` filter form?

The following code does not work either.

    <form method="post" action=".">
       {% with form_show_labels=False %}
       {{ form|crispy }}
       {% endwith %}
    </form>

**Comment by carltongibson** [comment]
> How do I prevent showing the labels and use the `{{ form|crispy }}` filter form?

Bottom line is you don't. See the [Using `{% crispy %}` tag because it rocks](http://django-crispy-forms.readthedocs.org/en/latest/filters.html#using-crispy-tag-because-it-rocks) section of the docs.
