### ISSUE TITLE
Crispy forms .wrap or .update_attributes buggy after previous creation of layout object?

### ISSUE THREAD

**Issue by MarcMueltin** [maraujop/django-crispy-forms#514]
Hi there, 

I posted an issue on GitHub some days ago, but no reply yet. So I hope you can help me directly. :)
Please have a look at http://stackoverflow.com/questions/32374203/crispy-forms-wrap-or-update-attributes-buggy-after-previous-creation-of-layout

Thanks, 
Marc

**Comment by MarcMueltin** [comment]
Hey there, 

I would very much appreciate a comment on this issue, since I need a solution this week. :)

Thanks, 
Marc

**Comment by carltongibson** [comment]
Always wise to try searching for your error. See #511
