### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by anhtran** [maraujop/django-crispy-forms#524]
Version 4 will come soon. We should be ready to go with that.

**Comment by zoidbergwill** [comment]
The changes to [forms](http://v4-alpha.getbootstrap.com/migration/#forms) are rather minor, so it shouldn't be too hard to add support.

**Comment by anhtran** [comment]
Yes, I know. But it will be a little bit confusing when put `bootstrap3` in the settings.

**Comment by zoidbergwill** [comment]
Yes, I know. We should add separate version 4 support. I'd happily do it.

**Comment by pydanny** [comment]
:+1:

**Comment by carltongibson** [comment]
This is on my radar but I'd **very happily** accept a pull request that took it on.

My thoughts have got as far as:

1. Copy and rename existing bootstrap3 template pack.
2. Edit as needed.

If we can get something out soon then we can let users report issues whilst Bootstrap 4 is still alpha/beta level. That would be good.

**Comment by zoidbergwill** [comment]
@carltongibson my plan was doing the same thing.

Here's my work so far: https://github.com/maraujop/django-crispy-forms/compare/dev...zoidbergwill:dev

I just need to test the `.form-group` no longer mixing in the `.row` class, so it’s now required for grid layouts stuff some more, to make sure all the tests are doing the right thing. 

I'll go over everything I've done so far again and test it in the morning, before I update the docs and make a PR.

**Comment by carltongibson** [comment]
> Any input is appreciated. :)

Open a PR as soon as you need to. If you list Todo in the description I can help you work through it.

**Comment by zoidbergwill** [comment]
@carltongibson Thanks. I've made a [PR](https://github.com/maraujop/django-crispy-forms/issues/528)
