### ISSUE TITLE
Crispy load hard my database (20 times!)

### ISSUE THREAD

**Issue by fellipeh** [maraujop/django-crispy-forms#534]
Hello, I need to create a inlineformset, and work with crispy.. (same model in my last issue)... I have these Helper:

```
class OfertasFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(OfertasFormSetHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        self.layout = Layout(
            Field('Field1', css_class="select-chosen"),
            'Field2',
            'Field3',
            Field('Field4', css_class='form-control input-datepicker-close', placeholder="dd/mm/yyyy",
                  data_date_format="dd/mm/yyyy"),
            'Field5',
            FormActions(Submit('submit', 'Save', css_class='btn btn-primary'),
                        )
        )
```

and my view:

```
    ofertasinlineformset = inlineformset_factory(Author, Books,
                                                     exclude=(),
                                                     can_delete=False)
    helper = OfertasFormSetHelper()
    helper.template = 'bootstrap/table_inline_formset.html'

```

When I go to Django Debug-toolbar... show me, my view try to go in my database for each record in mu inlineformset 20 times!!!

Here is my screenshot (sorry, but my models is in pt-BR)
![screen shot 2015-10-15 at 10 47 04](https://cloud.githubusercontent.com/assets/2904206/10515494/2bae8d78-732a-11e5-98c0-8708c559db3c.png)

Why is these happen!?

Cheers

**Comment by Stranger6667** [comment]
Hello, @fellipeh 
Probably, some `prefetch_related` or `select_related` calls to your queryset could help to reduce queries number. I've faced with same problems some time ago and solved it with that. But here I'm out of context of your app, so it is just general solution for such problems.
