### ISSUE TITLE
Field order is unpredictable without explicit layout

### ISSUE THREAD

**Issue by mverleg** [maraujop/django-crispy-forms#538]
When not using an explicit layout, the order of fields is unpredictable. Within a server session it's consistent but between server restarts it's pseudo-random.

I can't imagine that this is the desired behaviour, especially when Form.Meta.fields is set.

I think a likely reason is in `helper.py` around line 299, where it says 

    left_fields_to_render = fields - form.rendered_fields

I understand that using sets is much more convenient than calculating the difference manually, but sets are unordered so this has downsides. You'll want something like this http://stackoverflow.com/a/6486513/723090 . Sorry for not sending a pull request.

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.

**Comment by mverleg** [comment]
Okay, it seems important to me, so I made a pull request https://github.com/maraujop/django-crispy-forms/pull/539
