### ISSUE TITLE
Support for Materialize

### ISSUE THREAD

**Issue by awwester** [maraujop/django-crispy-forms#546]
I'm making a branch adding Materialize as a template option. There are a various `crispy-forms-materialize` repos out there, but none of them are a fork of django-crispy-forms, they're just disparate projects added separately from django-crispy-forms.

Before putting time into it, I'm curious if there is interest in adding support for Materialize as a template pack? I'm not finding any topics on that here in github, I apologize if this topic has already been addressed. I'm guessing it's been decided it's not worth the maintenance, or else Foundation would have been included by now, but I thought I'd check just in case.

**Comment by jingle1000** [comment]
I'd be interested in having this feature!
