### ISSUE TITLE
html5_required set default to True

### ISSUE THREAD

**Issue by wjurkowlaniec** [maraujop/django-crispy-forms#552]
What do you think?

**Comment by carltongibson** [comment]
Not sure. But probably no.

**Comment by wjurkowlaniec** [comment]
Why? HTML5 form validation is a standard now, and I if you don't read the [documentation](http://django-crispy-forms.readthedocs.org/en/d-0/tags.html)  till the end you're trying to figure out why required is not showing in inputs

**Comment by carltongibson** [comment]
Required is set at the Django level. https://docs.djangoproject.com/en/1.9/ref/forms/fields/#core-field-arguments

It's not Crispy Form's responsibility.

**Comment by jcass77** [comment]
Apologies for hijacking an old issue.

I've been thinking about this for a while and wonder if we should not consider the two issues separately:

1. setting a field to 'required' - as @carltongibson rightly points out, this should be done at the Django level.

2. rendering the required fields on screen using the browser-supported HTML5 UI elements.

Enough time has probably gone by that we can reconsider enabling HTML5 rendering support by default. This will bring django-crispy-forms in line with how most users would expect to view and interact with required fields when filling in forms these days, I think.
