### ISSUE TITLE
Deprecation warnings when used with Django 1.9

### ISSUE THREAD

**Issue by jandd** [maraujop/django-crispy-forms#553]
When used in a Django 1.9 project crispy-forms code produces some deprecation warnings:

    python2.7/site-packages/crispy_forms/utils.py:157: RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.
      html = template.render(context)

    python2.7/site-packages/crispy_forms/layout.py:199: RemovedInDjango110Warning: The  context_instance argument of render_to_string is deprecated.
      return render_to_string(template, {'input': self}, context)

    python2.7/site-packages/django/template/loader.py:97: RemovedInDjango110Warning: render() must be called with a dict, not a RequestContext.
      return template.render(context, request)

I'm not sure whether this list is complete, but this is all I get in the test suite of one of my projects. I have not observed any wrong behavior in my application yet.

**Comment by kavdev** [comment]
Two more instances for you:

```
python3.4/site-packages/crispy_forms/bootstrap.py:90: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.
  return render_to_string(template, extra_context, context)

python3.4/site-packages/crispy_forms/templatetags/crispy_forms_tags.py:222: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return template.render(c)
```

[Related information:](https://docs.djangoproject.com/en/1.9/howto/custom-template-tags/#auto-escaping-considerations)
> Changed in Django 1.8:
> 
> The template attribute of Context objects was added in Django 1.8. context.template.engine.get_template must be used instead of django.template.loader.get_template() because the latter now returns a wrapper whose render method doesn’t accept a Context.

**Comment by kavdev** [comment]
I'm going to put in a pull request in a bit, but fair warning: keeping < 1.8 compatibility will result in some ugly code.

**Comment by carltongibson** [comment]
If anyone wants a Christmas project, I'd be happy to take a PR on these issues! 😃

**Comment by kavdev** [comment]
@carltongibson: #554? 😃

**Comment by carltongibson** [comment]
Already merged, but there are other warnings right?

**Comment by kavdev** [comment]
Nope, got all of them. They are part of the same deprecation.

**Comment by carltongibson** [comment]
@kavdev OK. thanks for the input! 

FYI I'm looking for a release the w/b 4th Jan

**Comment by kavdev** [comment]
@carltongibson: Sounds good. #555

**Comment by carltongibson** [comment]
Good work @kavdev. Thanks.

**Comment by jandd** [comment]
@kavdev thanks a lot
