### ISSUE TITLE
The README file is misleading in regard to supported Python/Django versions

### ISSUE THREAD

**Issue by andreyfedoseev** [maraujop/django-crispy-forms#566]
The README files says that:

> django-crispy-forms supports Django 1.3 or higher with Python 2.6.x, Python 2.7.x and Python 3.3.x.

But the actual requirements are Python 2.7+ and Django 1.9+ (based on `tox.ini`).

**Comment by carltongibson** [comment]
Yep. Dead right. A PR there would be AWESOME! Thanks!

**Comment by kevin-brown** [comment]
Based on `.travis.yml`, the requirements are Python 2.7/Python 3.2+ and Django 1.8+
