### ISSUE TITLE
Problems with djangos new DurationField

### ISSUE THREAD

**Issue by pritstift** [maraujop/django-crispy-forms#567]
I have a DurationField ind a model. When rendereing the template (of course using crispy_forms), i get an error regarding the durationfield.

[Gist File](https://gist.github.com/pritstift/6b199040759cf37e2a2b#file-gistfile1-txt)

Is crispy forms not ready yet for django's new durationfield ?

**Comment by carltongibson** [comment]
Hmmm. Not sure. Can you create a minimal test case to try and isolate the issue?

**Comment by carltongibson** [comment]
This isn't actionable as is. If more info comes to light we can reopen.
