### ISSUE TITLE
Commit c994f71 causes ValueError

### ISSUE THREAD

**Issue by Laodicean** [maraujop/django-crispy-forms#568]
Running crispy 1.6.0 (which isn't tagged or released on git by the way) with django 1.8.8 causes a value error to arise when rendering layouts. I also use django-cms.

https://dpaste.de/5cFQ

I haven't had time to take a good look into this. At a glance it looks like the context object is being given something that it can't flatten -- whether this is happening in crispy, I'm unsure.

**Comment by Laodicean** [comment]
Upon further inspection it looks like this is an issue caused by djangocms.

**Comment by carltongibson** [comment]
> ... crispy 1.6.0 (which isn't tagged or released on git by the way) ...

https://github.com/maraujop/django-crispy-forms/releases/tag/1.6.0
