### ISSUE TITLE
Button Group Support

### ISSUE THREAD

**Issue by scuml** [maraujop/django-crispy-forms#580]
Searched online and through the source and cannot find how one can implement button groups?  Is this possible in 1.6.0?  I'd be interested in coding a patch to support this feature if not.

http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons
http://foundation.zurb.com/sites/docs/v/5.5.3/components/button_groups.html

> Tags: button-group btn-group

**Comment by scuml** [comment]
There are two different patterns at play here.  The standard button group can be implemented with the following code:
```
ButtonHolder(
    Submit('save_changes', 'Save changes', css_class="btn-primary"),
    Submit('cancel', 'Cancel'),
    css_class='btn-group'
),
```

The checkbox/radio button group (http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons) requires a more significant coding change to the inline radio select code:
- `class="btn-group" data-toggle="buttons"` needs to be added to a div after the label element, that wraps the radio inputs and labels
- an `active` class needs to be added to the radio label if initial value is set
- the individual radio labels need a user defined class

This doesn't fit naturally into the crispy code base.  Attaching the zipped class and template to manually add to any project that might need it.  

**Implementation**
```
from custom_crispy import RadioButtons, CheckboxButtons
helper.layout = Layout(
        RadioButtons('radio_buttons', option_label_class="btn btn-info",),
        CheckboxButtons('checkboxes'),
)
```

**Result**
![screen shot 2016-05-09 at 11 12 28 am](https://cloud.githubusercontent.com/assets/1790447/15117804/3b250eee-15d7-11e6-91b6-f754753567c6.png)

**Attached Code**
[radiocheckbox-buttongroups.zip](https://github.com/maraujop/django-crispy-forms/files/255247/radiocheckbox-buttongroups.zip)

**Comment by scuml** [comment]
Branch diff if anyone is interested.

**Comment by carltongibson** [comment]
@scuml Thanks for the input here. It's interesting. Not sure what to say re an issue or not. Maybe one for the docs or a blog post or something.

**Comment by fladi** [comment]
I need this regularly, can we get this merged somehow?

**Comment by zoidbergwill** [comment]
It'd be awesome to get some tests and docs on that branch, but if you're willing to make a PR for that branch, that'd be awesome, and I'll have a look when I can.

**Comment by FlowFX** [comment]
Thanks @scuml for the solution to my problem! :D
