### ISSUE TITLE
table_inline_formset.html bootstrap templates don't call form.media

### ISSUE THREAD

**Issue by JoshAddington** [maraujop/django-crispy-forms#584]
The `{{form.media}}` tag is only in the `display_form.html` and `uni_form.html` templates. The tag is not in `table_inline_formset.html`, and neither of the templates that have the tag are called in the `table_inline_formset.html` template.

Is there a reason that the `form.media` tag is not in the `table_inline_formset.html` template, or was that simply an oversight?

**Comment by carltongibson** [comment]
> Is there a reason...

Probably just that it's a bit of on edge-case. 

If you need this I'd say override the template in your own project. 

It's not something I want to take on as an active issue. If you fancy putting together a documented, tested pull request that covers your use-case, that would be welcome.
