### ISSUE TITLE
broken compatibility with django 1.4.22 in release 1.6.0 

### ISSUE THREAD

**Issue by Numerico** [maraujop/django-crispy-forms#587]
Django-crispy-forms **1.6.0** makes use of _RequestContext_'s **flatten** method, for instance [here](https://github.com/maraujop/django-crispy-forms/blob/1.6.0/crispy_forms/layout.py#L332).
But that method was only introduced in django>**1.7** (specifically in [this commit](https://github.com/django/django/commit/8274fa60f88607eb0e81908f049c391455956dd8)).
This causes an _AttributeError_ exception **'RequestContext' object has no attribute 'flatten'**
In my case when using the {% crispy form %} tag to enable FormHelper in an app using django 1.4.22.
I understand you're still supporting django>1.2, isn't it? In that case this would be a bug.

May be it could use some version check similar to [this](https://github.com/maraujop/django-crispy-forms/blob/c2c93cf9992622bbbf7bdbbcd9c0f1062506921f/crispy_forms/templatetags/crispy_forms_field.py#L186)?
I'm willing to help with code if necessary. 
Thank you

**Comment by kevin-brown** [comment]
> I understand you're still supporting django>1.2, isn't it?

Quoting from the README, this doesn't appear to be the case

> django-crispy-forms supports Python 2.7/Python 3.2+ and Django 1.8+

**Comment by Numerico** [comment]
Ok, thank you Kevin.
So, what version should I use for an app using django 1.4?
(It's not an option to upgrade the full app yet...)

**Comment by Numerico** [comment]
OK, it would be 1.5.2 in case anyone else wonders the same...
