### ISSUE TITLE
Span wrapper?

### ISSUE THREAD

**Issue by egbutter** [maraujop/django-crispy-forms#590]
Hi @maraujop are you open to including a Span wrapper in the layouts? I'm happy to submit a PR with this. I needed to wrap an input in a Span for typeahead.js support (http://www.runningcoder.org/jquerytypeahead/documentation/). For now I'm just using your HTML element, but Span is probably the "right" way to do this .. Thanks!

**Comment by carltongibson** [comment]
@egbutter This is something you'd use your own `Layout` for, or override the templates. It's not something that we'd add to the core template packs. 

(I'm going to close this but happy to discuss further if you care to elaborate.)

**Comment by egbutter** [comment]
Sure thing. I'm already using Layout, but there is no Span wrapper provided (as there is a Div). The reason that's not ideal is that I need to wrap an input in a span. Right now I'm accomplishing this with two HTML elements (one starting to span, the second one closing it). The mark-up I'm trying to replicate is in the previous link I sent. Thanks again,

**Comment by carltongibson** [comment]
Ah, right. You're suggesting adding a Span LayoutObject subclass? That might be looking at yes. Do you have such a class already?

**Comment by egbutter** [comment]
That's right, a Span LayoutObject subclass. I have not done it yet, but it looks trivial to implement, 99% of the code would be identical to Div. I could knock this and some tests out quickly, this morning. 

Probably worthy of a second issue#, but how do you guys feel about a templates/common/ dir, with some of the reused templates, especially those in templates/common/layout? There are some repeated templates across the bootstrap* and uniform dirs - notably templates/*/layout/div.html

**Comment by carltongibson** [comment]
Put together a PR. Happy to review.

I'd happily consider a simple method to allow template packs to fallback to a shared template if they did not provide one.

**Comment by egbutter** [comment]
Ok, thank you. I'll include this issue# in the PR.

**Comment by egbutter** [comment]
*Actually looks like I won't get to this until tonight ..

**Comment by carltongibson** [comment]
No rush. :-)
