### ISSUE TITLE
Keep getting this weird KeyError on production server

### ISSUE THREAD

**Issue by naglalakk** [maraujop/django-crispy-forms#596]
Hi. I'm using django-crispy-forms for all of my forms. Right now I have a subscription club running and some customers are getting errors. The weird thing is that this error only comes up randomly. When tailing the logs this is what I get:

    File "/home/donna/grill/askriftartilbod/venv/lib/python3.4/site-packages/crispy_forms/utils.py", line 74, in render_field
    field_instance = form.fields[field]
    KeyError: ''

Has anyone come across this error? Just wondering what might be causing this. I've looked over my forms and they all seem correct. I will spare you the details of posting all my code here but let me know if you want a more detailed look at my code

**Comment by carltongibson** [comment]
Hi @naglalakk

This isn't much to go on I'm afraid. 

You need to try and narrow it down to the smallest possible test case that shows the issue. 

> The weird thing is that this error only comes up randomly

This will make it hard. 

At this point you've got a bit of detective work to do before it's actionable. 

I'm going to close this for now. If you can narrow it down to something concrete and reproducible I'm happy to re-open. 

Sorry I can't be more help.

**Comment by naglalakk** [comment]
@carltongibson No worries, I understand. I will monitor my logs to see if this occurs again and report back if I figure out what is causing this. Thank you for the reply 👍

**Comment by carn1x** [comment]
I found a similar-ish error, I had the following code:

```
help_text_locked = HTML('<br><span class="help-inline info"><small><i>blah.</i></small></span>') if my_boolean else None

# ... and then later on ...
Div(help_text_locked, css_class='pull-right'), css_class='clearfix')
```

So there was a rare case where the `Div.fields = [None]` and spewing noise into my logs.

I fixed by changing `None` to `HTML('')`
