### ISSUE TITLE
 ImportError: No module named 'crispy_forms' 

### ISSUE THREAD

**Issue by francose** [maraujop/django-crispy-forms#598]
I have tried to install Django-crispy-forms and i got  ImportError: No module named 'crispy_forms' message as soon as I ran the server.
I am able to see it in my site-packages and whenever i say pip freeze while virtualenv activated i am able to see it. 

What exactly causes this ?

 File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'crispy_forms'

**Comment by pypetey** [comment]
Did you install it inside/outside virtualenv?

**Comment by carltongibson** [comment]
See the discussion on #377 for pointers — but, short of more to go on, it has to be something to do with your path settings. (Did you activate the virtualenv? etc)

**Comment by francose** [comment]
@carltongibson Thank you very much, it has something to do with PATHs definitely.

**Comment by francose** [comment]
@carltongibson  When i type pip freeze on my terminal in the "virtualenv" (activated), i keep getting my system's pip dependencies  which are not related to my "virtualenv" dependencies?Somebody told me that this is a path settings issue?
I use "pyhton3.5" but when i pip $PATH shows my systems "pyhton2.7" 

please help.
