### ISSUE TITLE
I want to make mdl template packs for django-crispy-forms.

### ISSUE THREAD

**Issue by RatanShreshtha** [maraujop/django-crispy-forms#606]
Material Design Lite lets you add a Material Design look and feel to your websites. I want to add mdl templates for django-crispy-forms.

How can I do that and is it possible that crispy forms will also have options for mdl along with bootstrap, bootstrap3, foundation and uni-form.

**Comment by carltongibson** [comment]
Hiya, 

I'm happy to link to any template packs from the docs, but I don't want to accept any more template packs as part of the core package. 

Create your pack. Put it online (GitHub?) and open a PR linking to it from the docs. That's it. :-)

I'm going to close this as an issue.
